version: "3.1"

services:
  postgreDB:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web_app:
    build: .
    ports:
      - "8000:8000"


volumes:
  pgdata:
