# Generated by Django 4.0.4 on 2022-05-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=11)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trade.city')),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=124)),
                ('phone', models.CharField(max_length=11)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trade.city')),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sort', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=64)),
                ('material', models.CharField(max_length=64)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trade.maker')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantity', models.SmallIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trade.client')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trade.tovar')),
            ],
        ),
    ]
